title: Ngoc (Jane) Dinh's Website
logo: https://i.imgur.com/2XburdGm.jpg
description: 

<br>New York, NY</br>
<br>Fordham University Class of 2020</br>


<a href="https://rpubs.com/ngocdinh1410">RPubs</a>


<a href="https://www.linkedin.com/in/ngoc-dinh-a7a2a561/">LinkedIn</a>


<a href="https://drive.google.com/file/d/1BlGbtP68rb3G8hwsVP8xqbZpExtc6DWQ/view?usp=sharing">Resume</a>

<a href="https://github.com/ngocdinh1410/">Github</a>


theme: jekyll-theme-minimal
