title: Ngoc (Jane) Dinh's Website
logo: https://i.imgur.com/RZVq6JC.jpg
description: >
My journey in Data Science
<br><br>
New York, NY
<br><br>
Fordham Univesity
<br><br>
theme: jekyll-theme-minimal
